config/routes.rb
Rails.application.routes.draw do

  resources :nuggets
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/nugget.rb
class Nugget < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/nuggets_controller.rb
class NuggetsController < ApplicationController
  before_action :set_nugget, only: [:show, :edit, :update, :destroy]

  # GET /nuggets
  # GET /nuggets.json
  def index
    @nuggets = Nugget.all
  end

  # GET /nuggets/1
  # GET /nuggets/1.json
  def show
  end

  # GET /nuggets/new
  def new
    @nugget = Nugget.new
  end

  # GET /nuggets/1/edit
  def edit
  end

  # POST /nuggets
  # POST /nuggets.json
  def create
    @nugget = Nugget.new(nugget_params)

    respond_to do |format|
      if @nugget.save
        format.html { redirect_to @nugget, notice: 'Nugget was successfully created.' }
        format.json { render :show, status: :created, location: @nugget }
      else
        format.html { render :new }
        format.json { render json: @nugget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nuggets/1
  # PATCH/PUT /nuggets/1.json
  def update
    respond_to do |format|
      if @nugget.update(nugget_params)
        format.html { redirect_to @nugget, notice: 'Nugget was successfully updated.' }
        format.json { render :show, status: :ok, location: @nugget }
      else
        format.html { render :edit }
        format.json { render json: @nugget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nuggets/1
  # DELETE /nuggets/1.json
  def destroy
    @nugget.destroy
    respond_to do |format|
      format.html { redirect_to nuggets_url, notice: 'Nugget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nugget
      @nugget = Nugget.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def nugget_params
      params.require(:nugget).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_link(name)
    controller_name == name ? 'active' : ''
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nuggets_helper.rb
module NuggetsHelper
end

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.erb

%button.btn.btn-secondary{"data-placement" => "top", "data-toggle" => "tooltip", :title => "Tooltip on top", :type => "button"}
  Tooltip on top
%button.btn.btn-secondary{"data-placement" => "right", "data-toggle" => "tooltip", :title => "Tooltip on right", :type => "button"}
  Tooltip on right
%button.btn.btn-secondary{"data-placement" => "bottom", "data-toggle" => "tooltip", :title => "Tooltip on bottom", :type => "button"}
  Tooltip on bottom
%button.btn.btn-secondary{"data-placement" => "left", "data-toggle" => "tooltip", :title => "Tooltip on left", :type => "button"}
  Tooltip on left


%button.btn.btn-lg.btn-danger{"data-content" => "And here's some amazing content. It's very engaging. Right?", "data-toggle" => "popover", :title => "Popover title", :type => "button"} Click to toggle popover

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    %meta{:content => "Compilation of scripts, snippets, tutorials for beginner developers", :name => "description"}/

    / Fonts and icons
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css", :rel => "stylesheet"}/

    %title Eureka | JEA
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body.dark-edition
    .wrapper
      = render 'shared/sidebar'
      .main-panel
        = render 'shared/navbar'
        .content
          .container-fluid
            = yield
        %footer.footer
          = render 'shared/footer'

app/views/nuggets/_form.html.haml
= form_with(model: nugget, local: true) do |form|
  - if nugget.errors.any?
    #error_explanation
      %h2
        = pluralize(nugget.errors.count, "error")
        prohibited this nugget from being saved:
      %ul
        - nugget.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :content
    = form.text_area :content
  .actions
    = form.submit

app/views/nuggets/edit.html.haml
%h1 Editing Nugget
= render 'form', nugget: @nugget
= link_to 'Show', @nugget
|
= link_to 'Back', nuggets_path

app/views/nuggets/index.html.haml
%p#notice= notice
%h1 Nuggets
%table
  %thead
    %tr
      %th Title
      %th Content
      %th{:colspan => "3"}
  %tbody
    - @nuggets.each do |nugget|
      %tr
        %td= nugget.title
        %td= nugget.content
        %td= link_to 'Show', nugget
        %td= link_to 'Edit', edit_nugget_path(nugget)
        %td= link_to 'Destroy', nugget, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Nugget', new_nugget_path

app/views/nuggets/new.html.haml
%h1 New Nugget
= render 'form', nugget: @nugget
= link_to 'Back', nuggets_path

app/views/nuggets/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @nugget.title
%p
  %strong Content:
  = @nugget.content
= link_to 'Edit', edit_nugget_path(@nugget)
|
= link_to 'Back', nuggets_path

app/views/shared/_footer.html.haml
.container-fluid
  %nav.float-left
    %ul
      %li
        = link_to 'View on Github', 'https://github.com/jess-alejo/eureka', target: '_blank'
  .copyright.float-right
    ©
    = "#{DateTime.now.utc.year}, made with"
    %i.material-icons favorite
    by
    = link_to 'saguiguilid', 'https://jea.com.ph', target: '_blank'
  / your footer here

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-transparent.navbar-absolute.fixed-top
  .container-fluid
    .navbar-wrapper
      = link_to controller_name.titleize, "#", class: 'navbar-brand'

    %button.navbar-toggler{"aria-controls" => "navigation-index", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.navbar-toggler-icon.icon-bar
      %span.navbar-toggler-icon.icon-bar
      %span.navbar-toggler-icon.icon-bar
    .collapse.navbar-collapse.justify-content-end
      %ul.navbar-nav
        %li.nav-item
          %a.nav-link{:href => "javascript:void(0)"}
            %i.material-icons notifications
            %p.d-lg-none.d-md-block
              Notifications
        / your navbar here

app/views/shared/_sidebar.html.haml
.sidebar{"data-background-color" => "black", "data-color" => "purple", "data-image" => image_path("sidebar-2.jpg")}
  /
    Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"
    
    Tip 2: you can also add an image using data-image tag
  .logo
    = link_to 'Eureka | JEA', root_path, class: 'simple-text log-normal'
  .sidebar-wrapper
    %ul.nav
      %li.nav-item{ class: active_link("home") }
        = link_to root_path, class: 'nav-link' do
          %i.material-icons dashboard
          %p Dashboard
      %li.nav-item{ class: active_link("nuggets") }
        = link_to nuggets_path, class: 'nav-link' do
          %i.material-icons smart_button
          %p Nuggets